### ISSUE TITLE
/lib/modules no build and source link

### ISSUE THREAD

**Issue by lucasperovani** [Re4son/Re4son-Pi-TFT-Setup#10]
I installed this tft kernel perfectly in raspberry pi 3 with a raspbian, but i want to activate the monitor mode  with this link here: https://github.com/seemoo-lab/nexmon, everything works fine untill i decide to put both together because  it says that build folder doesn't exit, please help me, can i put a normal kali build and source with the same version, or i can't?

**Comment by Re4son** [comment]
Interesting, thanks for letting me know about that.
I'll look into it and will get back to you

**Comment by lucasperovani** [comment]
thank you a lot!!

**Comment by Re4son** [comment]
Hi lupeeumeeu,

 

 

I’ve compiled the driver, firmware and nexutil for the Kali-Pi and included it in an updated kernel package.

You can download the package here:

 

https://www.whitedome.com.au/download/Kali-Pi-Kernels/re4son_kali-pi-tft_kernel_current.tar.xz

 

Just download to /usr/local/src and uncompress. It will contain a directory “nexmon” with those three files. Be careful though, once installed you cannot connect to any wifi AP’s though.

 

Please let me know how you go.

 

Many thanks,

Re4son

**Comment by lucasperovani** [comment]
Thanks a lot, but I was changing between the original firmware and the modified one, can I do the same thing to this in order to have monitor mode and WiFi when I want?

**Comment by lucasperovani** [comment]
Years thank you, I made a backup of the original firmware and a shell script to change between both :D
