### ISSUE TITLE
.xz or .gz?

### ISSUE THREAD

**Issue by nosarious** [Re4son/Re4son-Pi-TFT-Setup#11]
examining the directory you are directing people to in the description ( http://whitedome.com.au/download/Kali-Pi-Kernels/ ) I found the file mentioned has an .xz at the end, not .gz as you have listed.

is that an error in typing or is the file named incorrectly?

re4son_kali-pi-tft_kernel_current.tar.xz    or re4son_kali-pi-tft_kernel_current.tar.gz

**Comment by nosarious** [comment]
The untar line also needs changing due to the suffix.

For the record, changing to .xz in both cases did the trick.

**Comment by Re4son** [comment]
Good find thanks for that.
It's been changed to xz but I have missed to adjust the README. Will do it straight away.
The correct and up to date walk through is maintained here:
https://www.whitedome.com.au/re4son/re4son-kernel

Many thanks,
Re4son
